### PR TITLE
OgreVis::loadMeshFile: Support URDFs with package:// paths

### PR DESCRIPTION
**Pull request by wxmerkt**
This commit adds support to resolve paths that include `package://` without relying on a ROS package. It is based on the assumption that a package named "my_package" exists on a full path that includes "my_package". This is always true for install spaces, and should be true for devel spaces unless manually changed. 

If package:// is not part of the path, the existing behaviour is preserved. 
If package:// is part of the path, which currently throws an exception, the relative path of the URDF w.r.t. the root of the package is removed as well as the package://my_package string.

It would be great if the same behaviour could also be replicated in raisimLib for loading collision meshes.

This way we can directly load any ROS-default URDF without modifying them for RaiSim by dropping the `package://my_package/` string.

### CODE REVIEW

**Comment by jhwangbo** [comment]
Thanks for the PR. This is a useful feature

**Comment by wxmerkt** [comment]
Thank you for the quick turnaround, Jemin. It would be great if you could port this to raisimLib please and upload a new lib with it enabled :-).

Thanks for providing such an awesome simulator,
Wolfgang

**Comment by jhwangbo** [comment]
I currently can't push to raisimLib. I am waiting for ETH to sort out the license. I hope this happens fast and I can push v1.0... which will have better support for Unity, Matlab, ball joints, scripted world, etc

**Comment by wxmerkt** [comment]
Thanks for the update and hope it gets sorted :-)

**Pull request merged**
